### ISSUE TITLE
KeyError: 'TotalCollectorsTokensSpent'

### ISSUE THREAD

**Issue by RoboticEarthling** [sergiodias25/Snap_Player_Stats#3]
I am getting this error when I run generate_file.py

```
C:\Users\asdf>C:\Users\asdf\Downloads\Snap_Player_Stats-main\generate_file.py
Traceback (most recent call last):
  File "C:\Users\asdf\Downloads\Snap_Player_Stats-main\generate_file.py", line 2, in <module>
    import assets.data_parser as data_parser
  File "C:\Users\asdf\Downloads\Snap_Player_Stats-main\assets\data_parser.py", line 410, in <module>
    reload_file()
  File "C:\Users\asdf\Downloads\Snap_Player_Stats-main\assets\data_parser.py", line 93, in reload_file
    totalCollectorsTokensSpent = data['ServerState']['Account']['TotalCollectorsTokensSpent']
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'TotalCollectorsTokensSpent'
```

I'm guessing this is because I have not spent any tokens. Hopefully this is an easy fix!

**Comment by sergiodias25** [comment]
Just pushed a change to prevent this error from happening.
Hoping it works now!

**Comment by RoboticEarthling** [comment]
Yes, it works perfectly now, thank you!
